name: Release new version
on:
  workflow_dispatch:
  pull_request:
    types:
      - closed

jobs:
  create_release_pr:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: create release PR
      run: gh pr create -H main -B v0.1 --title 'Deployment <date>' --body 'Auto-created triggered by merge into main'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
