name: Release new version
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: create release PR
      run: gh pr create -H main -B v0.1 --title 'Release <date>' --body 'Auto-created triggered by merge into main'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
